### ISSUE TITLE
Moving between devices

### ISSUE THREAD

**Issue by TerryBradford** [mailvelope/keyserver#64] opened 2018-02-16 09:39 UTC
I wondered if the private key can remain persistent - e.g. if I create a key on on device within my chrome browser and then logout and in at another device if this can follow me - my thought might be to have the key in a home drive or in the case of chrome os it link to a google drive location ? 

presently when I move from one device to another I have to re-import my private key before I can send secure mail.

**Comment by dkg** [comment] 2019-04-03 18:26
Yes, you'll need to transfer your private key from one device to another in order to be able to decrypt mail.

But this doesn't seem relevant to the mailvelope keyserver (where the issue is currently reported), because the keyserver is specifically about distributing public keys, not private keys.  I recommend closing this issue or moving it to a more relevant forum.

**Closed** 2019-04-04 06:30 UTC
